name: Get Last Commit User IDs

on:
  workflow_dispatch:

jobs:
  list-committers:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      ORG_NAME: actions-test-86

    steps:
      - name: Verify gh auth
        run: |
          gh auth status

      - name: Debug GitHub Access
        run: |
          echo "ORG_NAME=$ORG_NAME"

          echo "Authenticated user:"
          gh auth status

          echo "Testing org access..."
          gh api "/orgs/$ORG_NAME"
